# The docker image for zk_evm.
zk_evm_image: leovct/zk_evm:v0.6.0

# Type 1 Prover - Worker Configuration
worker:
  # Enable or disable the HPA worker autoscaler.
  # If disabled, the number of workers deployed will be set according to `minWorkerCount`.
  autoscaler: false

  # The minimum number of worker pods to maintain.
  # The Horizontal Pod Autoscaler (HPA) will not scale down below this value.
  minWorkerCount: 5

  # The maximum number of worker pods to scale up to.
  # We start with 2 nodes, so we limit the maximum workers to 8 (4 per node).
  maxWorkerCount: 8

  # Worker flags.
  flags:
    - --serializer=postcard
    - --runtime=amqp
    - --persistence=disk
    - --load-strategy=monolithic

  # Worker environment variables.
  env:
    RUST_BACKTRACE: full
    RUST_LOG: info
    RUST_MIN_STACK: 33554432
    # Recommended circuit sizes by Robin.
    # https://0xpolygon.slack.com/archives/C0772FWR8D7/p1721390017860929?thread_ts=1721348826.760799&cid=C0772FWR8D7
    ARITHMETIC_CIRCUIT_SIZE: 16..25
    BYTE_PACKING_CIRCUIT_SIZE: 8..25
    CPU_CIRCUIT_SIZE: 12..27
    KECCAK_CIRCUIT_SIZE: 14..25
    KECCAK_SPONGE_CIRCUIT_SIZE: 9..20
    LOGIC_CIRCUIT_SIZE: 12..25
    MEMORY_CIRCUIT_SIZE: 17..28

  resources:
    # Resource requests are used by the Kubernetes scheduler to decide which node to place the pod on.
    requests:
      memory: 24G
      cpu: 5

    # Resource limits are enforced by the Kubernetes kubelet to prevent containers from using more resources than specified.
    limits:
      memory: 230G
      cpu: 50

# RabbitMQ Configuration
rabbitmq:
  cluster:
    # The Docker image for RabbitMQ.
    image: rabbitmq:3.13

    # The number of nodes in the RabbitMQ cluster.
    # It is recommended to use an odd number of nodes for better fault tolerance.
    # https://www.rabbitmq.com/docs/clustering#node-count
    nodeCount: 1

    # The default username for RabbitMQ.
    username: guest

    # The default password for RabbitMQ.
    password: guest

  # Horizontal Pod Autoscaler Configuration
  hpa:
    # The interval (in seconds) at which KEDA (Kubernetes Event-driven Autoscaler) will check the
    # queue length and scale the deployment accordingly.
    pollingInterval: 10

# Jumpbox Configuration
jumpbox:
  # The Docker image for the jumpbox (a secure entrypoint for accessing the cluster).
  image: leovct/zero-jumpbox:v0.6.0-1
