# Type 1 Prover Configuration
worker:
  #image: leovct/zero-bin-worker:develop
  image: nginx:latest

leader:
  image: leovct/zero-bin-leader:develop

rabbitmq:
  # RabbitMQ Cluster Configuration
  cluster:
    # The RabbitMQ image to use.
    image: rabbitmq:3.13.3
    # The number of nodes in the RabbitMQ cluster.
    # It is highly advised to use an odd number of nodes (https://www.rabbitmq.com/docs/clustering#node-count).
    nodeCount: 3
    # The default username.
    username: guest
    # The default password.
    password: guest

  # Horizontal Pod Autoscaler Configuration (RabbitMQ Queue)
  hpa:
    # The name of the queue to monitor.
    queue: hello
    # The interval (in seconds) at which KEDA will check the queue length and scale the deployment accordingly.
    pollingInterval: 10
    # The minimum number of workers to which the HPA can scale down.
    minWorkerCount: 1
    # The maximum number of workers to which the HPA can scale up.
    maxWorkerCount: 10
