apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-rolebinding
  namespace: kube-prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: zk-evm
roleRef:
  kind: Role
  name: port-forward-role
  apiGroup: rbac.authorization.k8s.io