name: ci

on:
  pull_request:
  push:
    branches: [main]

env:
  HELM_VERSION: "v3.15.0"
  TERRAFORM_VERSION: "v1.9.2"
  # Kubernetes operators
  RABBITMQ_CLUSTER_OPERATOR_VERSION: "4.3.14"
  KEDA_OPERATOR_VERSION: "2.14.2"
  PROMETHEUS_OPERATOR_VERSION: "61.3.1"

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}
      - uses: hashicorp/setup-terraform@v3
        with:
          version: ${{ env.TERRAFORM_VERSION }}

      - name: Lint helm chart
        run: helm lint ./helm
      - name: Lint terraform config
        run: terraform fmt --check

  helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Create Kind cluster
        uses: helm/kind-action@v1.9.0

      - name: Install RabbitMQ Cluster Operator
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm install rabbitmq-cluster-operator bitnami/rabbitmq-cluster-operator \
            --version ${{ env.RABBITMQ_CLUSTER_OPERATOR_VERSION }} \
            --namespace rabbitmq-cluster-operator \
            --create-namespace

      - name: Install KEDA Operator
        run: |
          helm repo add kedacore https://kedacore.github.io/charts
          helm repo update
          helm install keda kedacore/keda \
            --version ${{ env.KEDA_OPERATOR_VERSION }} \
            --namespace keda \
            --create-namespace

      - name: Install Prometheus Operator
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm install prometheus-operator prometheus-community/kube-prometheus-stack \
            --version ${{ env.PROMETHEUS_OPERATOR_VERSION }} \
            --namespace kube-prometheus \
            --create-namespace

      - name: Render helm template
        run: helm template test --namespace zero --create-namespace ./helm

      - name: Install helm chart
        run: helm install test --namespace zero --create-namespace ./helm
