name: Docker Image Builder Cron

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6 AM Paris time (UTC+2).
  workflow_dispatch:

env:
  ZERO_BIN_BRANCH_OR_COMMIT: main

concurrency:
  group: docker-image-builder-cron-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  zero-bin:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - leader
          - worker

    steps:
      - uses: actions/checkout@v4

      - name: Clone zero-bin repository
        working-directory: /opt
        run: |
          git clone https://github.com/0xPolygonZero/zero-bin.git
          cd zero-bin
          git checkout ${{ env.ZERO_BIN_BRANCH_OR_COMMIT }}

      - name: Apply patch
        working-directory: /opt/zero-bin
        run: patch -p1 -i ${{ github.workspace }}/docker/${{ matrix.image }}.diff

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: /opt/zero-bin
          file: /opt/zero-bin/${{ matrix.image }}.Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zero-bin-${{ matrix.image }}:${{ env.ZERO_BIN_BRANCH_OR_COMMIT }}
          platforms: linux/amd64,linux/arm64
          push: true

  zero-jumpbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/jumpbox.Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/zero-jumpbox:0.1.0
          platforms: linux/amd64,linux/arm64
          push: true
