name: Helm Lint and Test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: helm-lint-and-test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
        with:
          version: v3.15.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true
      - uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
